import { buildsFindAll, buildsFindById } from "../../src/api/builds";
import { mockAxios } from "../../mocks/axios";
import { Build, Builds } from "../../src/types";

it("should find the builds", async () => {
  const expected: Builds = [
    {
      id: 1,
      title: "Best Build Ever",
      description: "This is a nice test build",
      hero_id: 27,
      role: "midlane",
      crest_id: 21,
      item1_id: 144,
      item2_id: 179,
      item3_id: 168,
      item4_id: 114,
      item5_id: 150,
      skill_order: [1, 4, 1, 2, 1, 3, 1, 4, 1, 4, 3, 4, 4, 2, 2, 3, 2, 2],
      upvotes_count: 27,
      downvotes_count: 7,
      created_at: "2023-05-19T01:59:10.979Z",
      updated_at: "2023-09-21T00:25:43.074Z",
      author: "Armageddon",
      modules: [
        {
          title: "Flex Options",
          item1_id: 162,
          item2_id: 124,
          item3_id: 140,
          item4_id: null,
          item5_id: null,
          item6_id: null,
        },
        {
          title: "Alternative Crests Ordered By Viability",
          item1_id: 26,
          item2_id: 25,
          item3_id: 27,
          item4_id: null,
          item5_id: null,
          item6_id: null,
        },
        {
          title: "Mage Bruiser Morigesh (Offlane)",
          item1_id: 26,
          item2_id: 114,
          item3_id: 166,
          item4_id: 124,
          item5_id: 176,
          item6_id: 144,
        },
        {
          title: "Offlane Damage Flex Options",
          item1_id: 140,
          item2_id: 168,
          item3_id: 178,
          item4_id: null,
          item5_id: null,
          item6_id: null,
        },
        {
          title: "Offlane Tank Flex Options",
          item1_id: 156,
          item2_id: 139,
          item3_id: 118,
          item4_id: 163,
          item5_id: null,
          item6_id: null,
        },
        {
          title: "Alternative OFFLANE Crests Ordered By Viability",
          item1_id: 44,
          item2_id: 42,
          item3_id: null,
          item4_id: null,
          item5_id: null,
          item6_id: null,
        },
      ],
    },
    {
      id: 2,
      title: "Second Best Build Ever",
      description: "Another nice test build",
      hero_id: 2,
      role: "offlane",
      crest_id: 21,
      item1_id: 144,
      item2_id: 179,
      item3_id: 168,
      item4_id: 114,
      item5_id: 150,
      skill_order: [1, 4, 1, 2, 1, 3, 1, 4, 1, 4, 3, 4, 4, 2, 2, 3, 2, 2],
      upvotes_count: 27,
      downvotes_count: 7,
      created_at: "2023-05-19T01:59:10.979Z",
      updated_at: "2023-09-21T00:25:43.074Z",
      author: "Armageddon",
      modules: [
        {
          title: "Flex Options",
          item1_id: 162,
          item2_id: 124,
          item3_id: 140,
          item4_id: null,
          item5_id: null,
          item6_id: null,
        },
        {
          title: "Alternative Crests Ordered By Viability",
          item1_id: 26,
          item2_id: 25,
          item3_id: 27,
          item4_id: null,
          item5_id: null,
          item6_id: null,
        },
        {
          title: "Mage Bruiser Morigesh (Offlane)",
          item1_id: 26,
          item2_id: 114,
          item3_id: 166,
          item4_id: 124,
          item5_id: 176,
          item6_id: 144,
        },
        {
          title: "Offlane Damage Flex Options",
          item1_id: 140,
          item2_id: 168,
          item3_id: 178,
          item4_id: null,
          item5_id: null,
          item6_id: null,
        },
        {
          title: "Offlane Tank Flex Options",
          item1_id: 156,
          item2_id: 139,
          item3_id: 118,
          item4_id: 163,
          item5_id: null,
          item6_id: null,
        },
        {
          title: "Alternative OFFLANE Crests Ordered By Viability",
          item1_id: 44,
          item2_id: 42,
          item3_id: null,
          item4_id: null,
          item5_id: null,
          item6_id: null,
        },
      ],
    },
  ];

  const client = mockAxios(expected);
  const withClient = buildsFindAll(client);
  const response = await withClient();
  expect(response).toEqual(expected);
  expect(response.length).toBe(expected.length);
});

it("should find a build by Id", async () => {
  const expected: Build = {
    id: 1,
    title: "Test Build",
    description: "Test Build Description",
    hero_id: 27,
    role: "midlane",
    crest_id: 21,
    item1_id: 144,
    item2_id: 179,
    item3_id: 168,
    item4_id: 114,
    item5_id: 150,
    skill_order: [1, 4, 1, 2, 1, 3, 1, 4, 1, 4, 3, 4, 4, 2, 2, 3, 2, 2],
    upvotes_count: 27,
    downvotes_count: 7,
    created_at: "2023-05-19T01:59:10.979Z",
    updated_at: "2023-09-21T00:25:43.074Z",
    author: "Armageddon",
    modules: [
      {
        title: "Flex Options",
        item1_id: 162,
        item2_id: 124,
        item3_id: 140,
        item4_id: null,
        item5_id: null,
        item6_id: null,
      },
      {
        title: "Alternative Crests Ordered By Viability",
        item1_id: 26,
        item2_id: 25,
        item3_id: 27,
        item4_id: null,
        item5_id: null,
        item6_id: null,
      },
      {
        title: "Mage Bruiser Morigesh (Offlane)",
        item1_id: 26,
        item2_id: 114,
        item3_id: 166,
        item4_id: 124,
        item5_id: 176,
        item6_id: 144,
      },
      {
        title: "Offlane Damage Flex Options",
        item1_id: 140,
        item2_id: 168,
        item3_id: 178,
        item4_id: null,
        item5_id: null,
        item6_id: null,
      },
      {
        title: "Offlane Tank Flex Options",
        item1_id: 156,
        item2_id: 139,
        item3_id: 118,
        item4_id: 163,
        item5_id: null,
        item6_id: null,
      },
      {
        title: "Alternative OFFLANE Crests Ordered By Viability",
        item1_id: 44,
        item2_id: 42,
        item3_id: null,
        item4_id: null,
        item5_id: null,
        item6_id: null,
      },
    ],
  };

  const client = mockAxios(expected);
  const withClient = buildsFindById(client);
  const response = await withClient(1);
  expect(response).toEqual(expected);
  expect(response.title).toBe("Test Build");
});
