export const Heroes = {
  Countess: "Countess",
  Crunch: "Crunch",
  Dekker: "Dekker",
  Drongo: "Drongo",
  FengMao: "FengMao",
  Gadget: "Gadget",
  Gideon: "Gideon",
  Greystone: "Greystone",
  Grux: "Grux",
  Howitzer: "Howitzer",
  Kira: "Huntress",
  TheFey: "Fey",
  IggyAndScorch: "IggyScorch",
  LtBelica: "Lt. Belica",
  Morigesh: "Morigesh",
  Murdock: "Murdock",
  Muriel: "Muriel",
  Narbash: "Narbash",
  Kallari: "Kallari",
  Khaimera: "Khaimera",
  Phase: "Phase",
  Rampage: "Rampage",
  Revenant: "Revenant",
  Riktor: "Riktor",
  Serath: "Serath",
  Sevarog: "Sevarog",
  Shinbi: "Shinbi",
  Sparrow: "Sparrow",
  Steel: "Steel",
  Twinblast: "Twinblast",
  Wraith: "Wraith",
  Zarus: "Lizard",
};
